id: 34eab780-c82e-40bb-8d21-d584654b502d
version: 1
name: a
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9b416c00-2fa9-4117-85c1-cdbcbc849359
    type: start
    task:
      id: 9b416c00-2fa9-4117-85c1-cdbcbc849359
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
