id: 2024b257-b894-43f6-8b6e-7f5d5bb35fdc
version: 1
name: a
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1d1e3746-6058-4c53-8d1f-c437978b89f2
    type: start
    task:
      id: 1d1e3746-6058-4c53-8d1f-c437978b89f2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
