description: |-
  Enrich an endpoint by hostname using one or more integrations.
  Supported integrations:
  - Active Directory Query v2
  - McAfee ePolicy Orchestrator
  - Carbon Black Enterprise Response v2
  - Cylance Protect v2
  - CrowdStrike Falcon Host
id: Endpoint Enrichment - Generic v2.1
inputs:
- description: The hostname of the endpoint to enrich.
  key: Hostname
  required: false
  value:
    complex:
      accessor: Hostname
      root: Endpoint
      transformers:
      - operator: uniq
name: Endpoint Enrichment - Generic v2.1
outputs:
- contextPath: Endpoint
  description: The endpoint object of the endpoint that was enriched.
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostnames of the endpoints that were enriched.
  type: string
- contextPath: Endpoint.OS
  description: The operating systems running on the endpoints that were enriched.
  type: string
- contextPath: Endpoint.IP
  description: A list of the IP addresses of the endpoints.
- contextPath: Endpoint.MAC
  description: A list of the MAC addresses of the endpoints that were enriched.
- contextPath: Endpoint.Domain
  description: The domain names of the endpoints that were enriched.
  type: string
- contextPath: CylanceProtectDevice
  description: The device information about the hostname that was enriched using Cylance
    Protect v2.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 29bcd70f-1953-4061-84ce-4cde781ad9f7
      iscommand: false
      name: ""
      version: -1
    taskid: 29bcd70f-1953-4061-84ce-4cde781ad9f7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
      - "18"
      - "19"
      - "20"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 54895e0d-9904-4e62-8f45-ebd0d17ad5c9
      iscommand: false
      name: Endpoint Products
      type: title
      version: -1
    taskid: 54895e0d-9904-4e62-8f45-ebd0d17ad5c9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 440
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    note: false
    reputationcalc: 1
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: epo
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ""
      description: Checks if there is an active instance of the McAfee ePolicy Orchestrator
        integration enabled. integration enabled.
      id: c9799048-288a-40cc-8d2f-c561d0ea2f6b
      iscommand: false
      name: Is McAfee ePolicy Orchestrator enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: c9799048-288a-40cc-8d2f-c561d0ea2f6b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -650,
          "y": 750
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: isExists
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "24"
      - "1"
    note: false
    scriptarguments:
      value:
        simple: ${inputs.Hostname}
    separatecontext: false
    task:
      brand: ""
      description: Checks whether there is at least one endpoint to enrich (by hostname).
      id: efeca58b-3c8f-40aa-8c2e-f9e84257b1bb
      iscommand: false
      name: Is there an endpoint to enrich?
      type: condition
      version: -1
    taskid: efeca58b-3c8f-40aa-8c2e-f9e84257b1bb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 215
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      id: b95011d0-fd23-4e65-8ea9-560c5aead197
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b95011d0-fd23-4e65-8ea9-560c5aead197
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1310
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    reputationcalc: 1
    scriptarguments:
      searchText:
        complex:
          root: inputs.Hostname
          transformers:
          - operator: uniq
      verbose: {}
    separatecontext: false
    task:
      brand: epo
      description: Gets host information from McAfee ePolicy Orchestrator.
      id: 44a06d71-1772-47af-8d41-8c6dbdd149e7
      iscommand: true
      name: Get host information from McAfee ePO
      script: epo|||epo-find-system
      type: regular
      version: -1
    taskid: 44a06d71-1772-47af-8d41-8c6dbdd149e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -650,
          "y": 996
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    note: false
    reputationcalc: 1
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: carbonblack-v2
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Carbon Black Enterprise
        Response integration enabled.
      id: 9fa921fa-d196-40ba-8419-ed0c4f838ab8
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 9fa921fa-d196-40ba-8419-ed0c4f838ab8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -180,
          "y": 750
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    reputationcalc: 1
    scriptarguments:
      groupid: {}
      hostname:
        complex:
          root: inputs.Hostname
          transformers:
          - operator: uniq
      ip: {}
      sensor: {}
    separatecontext: false
    task:
      brand: carbonblack-v2
      description: Gets host information from Carbon Black Enterprise Response.
      id: 79f17c3a-2456-47d9-8e68-cc3d84ef01bd
      iscommand: true
      name: Get host information from Carbon Black Enterprise Response
      script: carbonblack-v2|||cb-sensor-info
      type: regular
      version: -1
    taskid: 79f17c3a-2456-47d9-8e68-cc3d84ef01bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 996
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "25"
    note: false
    reputationcalc: 1
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: FalconHost
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ""
      description: Checks if there is an active instance of the CrowdStrike Falcon
        Host integration enabled.
      id: 216aed2b-2f34-4c5e-8c54-60b978218896
      iscommand: false
      name: Is CrowdStrike Falcon Host enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 216aed2b-2f34-4c5e-8c54-60b978218896
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 730,
          "y": 750
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: d9d617d9-2efd-466e-8ce7-190f8db83b95
      iscommand: false
      name: McAfee ePolicy Orchestrator
      type: title
      version: -1
    taskid: d9d617d9-2efd-466e-8ce7-190f8db83b95
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -650,
          "y": 605
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 6cf08862-644d-479e-89ce-f9e173a8c562
      iscommand: false
      name: Carbon Black Enterprise Response
      type: title
      version: -1
    taskid: 6cf08862-644d-479e-89ce-f9e173a8c562
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -180,
          "y": 605
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 471d3862-a05c-42b1-871d-c1faa2fbb7a9
      iscommand: false
      name: Cylance Protect v2
      type: title
      version: -1
    taskid: 471d3862-a05c-42b1-871d-c1faa2fbb7a9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 270,
          "y": 605
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 5d371f29-3a4c-43c5-8f71-b383db2e5320
      iscommand: false
      name: CrowdStrike Falcon Host
      type: title
      version: -1
    taskid: 5d371f29-3a4c-43c5-8f71-b383db2e5320
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 730,
          "y": 605
        }
      }
  "22":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Active Directory Query v2
                - - left:
                      iscontext: true
                      value:
                        simple: state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "22"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "23"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Active Directory Query
        v2 integration enabled.
      id: 6a8160b7-fe32-4ab0-8396-e9bcafc98194
      iscommand: false
      name: Is Active Directory Query v2 enabled?
      type: condition
      version: -1
    taskid: 6a8160b7-fe32-4ab0-8396-e9bcafc98194
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -1226,
          "y": 655
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    reputationcalc: 1
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      name:
        complex:
          root: inputs.Hostname
          transformers:
          - operator: uniq
    separatecontext: false
    task:
      brand: Active Directory Query v2
      description: |-
        Uses Active Directory to retrieve detailed information about the computer of the account specified. The computer can be specified by name, email address, or as an Active Directory Distinguished Name (DN).
        If no filters are specified, returns all computers.
      id: 23c75906-3b4e-42e8-8e32-c883d5f06fb3
      iscommand: true
      name: Get host information from Active Directory
      script: Active Directory Query v2|||ad-get-computer
      type: regular
      version: -1
    taskid: 23c75906-3b4e-42e8-8e32-c883d5f06fb3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -1226,
          "y": 901
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 9706cc39-d338-44cd-8ee1-efc5ea95b04d
      iscommand: false
      name: Active Directory
      type: title
      version: -1
    taskid: 9706cc39-d338-44cd-8ee1-efc5ea95b04d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -1226,
          "y": 505
        }
      }
  "25":
    id: "25"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    scriptarguments:
      Hostname:
        complex:
          root: inputs.Hostname
          transformers:
          - operator: uniq
    separatecontext: false
    task:
      brand: ""
      description: Enrich an endpoint using CrowdStrike.
      id: 71baffa3-cd35-4cb0-8f50-0bd4c45fbc70
      iscommand: false
      name: CrowdStrike Endpoint Enrichment
      playbookName: CrowdStrike Endpoint Enrichment
      type: playbook
      version: -1
    taskid: 71baffa3-cd35-4cb0-8f50-0bd4c45fbc70
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 730,
          "y": 996
        }
      }
  "26":
    id: "26"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    separatecontext: true
    task:
      brand: ""
      id: abd18f95-6be8-4ba0-8f93-69c372ad88e5
      iscommand: false
      name: Endpoint Enrichment - Cylance Protect v2
      playbookName: Endpoint Enrichment - Cylance Protect v2
      type: playbook
      version: -1
    taskid: abd18f95-6be8-4ba0-8f93-69c372ad88e5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 270,
          "y": 996
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_25_yes": 0.54,
      "10_4_#default#": 0.11,
      "22_4_#default#": 0.2,
      "2_4_#default#": 0.11,
      "3_4_#default#": 0.53,
      "8_4_#default#": 0.19
    },
    "paper": {
      "dimensions": {
        "height": 1325,
        "width": 2336,
        "x": -1226,
        "y": 50
      }
    }
  }
