id: 52b4243f-8800-4716-8932-b0650d67888c
version: 1
name: Winitzky
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d8edf063-633e-400a-8ee2-971a46cea841
    type: start
    task:
      id: d8edf063-633e-400a-8ee2-971a46cea841
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
